package com.mobdeve.s19.group7.mco

import kotlin.random.Random
import androidx.compose.runtime.saveable.Saver

data class Profile(
    val name: String,
    val pictureResId: Int,
    var likedByUser: Boolean = false,
    val likesUser: Boolean = false,
    val messages: MutableList<Message> = mutableListOf(),
    val playlists: List<String> = emptyList(), // Add this property
)

// Define the `Message` class
data class Message(
    val sender: String, // The name of the sender
    val content: String // The content of the message
)

// Define a Saver for Profile
val ProfileSaver: Saver<Profile, Map<String, Any>> = Saver(
    save = { profile ->
        mapOf(
            "name" to profile.name,
            "pictureResId" to profile.pictureResId,
            "likedByUser" to profile.likedByUser,
            "likesUser" to profile.likesUser
        )
    },
    restore = { map ->
        Profile(
            name = map["name"] as String,
            pictureResId = map["pictureResId"] as Int,
            likedByUser = map["likedByUser"] as Boolean,
            likesUser = map["likesUser"] as Boolean
        )
    }
)


object SongDatabase {
    val allSongs = listOf(
        "Shadows - Olivia Rodrigo",
        "Dancing Lights - Charlie Puth",
        "Dreams - Taylor Swift",
        "Ocean Eyes - Ed Sheeran",
        "Memories - Sabrina Carpenter",
        "Breaking Free - Rihanna",
        "Sunset - Dua Lipa",
        "In the Rain - Adele",
        "Golden Hour - Kacey Musgraves",
        "Midnight Sky - Miley Cyrus",
        "Please Please Please - Sabrina Carpenter",
        "Firework - Katy Perry",
        "Rolling in the Deep - Adele",
        "Shape of You - Ed Sheeran",
        "Someone Like You - Adele",
        "Levitating - Dua Lipa",
        "Happier Than Ever - Billie Eilish",
        "Stay - Justin Bieber",
        "Perfect - Ed Sheeran",
        "Bad Habits - Ed Sheeran",
        "Drivers License - Olivia Rodrigo",
        "Deja Vu - Olivia Rodrigo",
        "Good 4 U - Olivia Rodrigo",
        "All Too Well - Taylor Swift",
        "Anti-Hero - Taylor Swift",
        "Blank Space - Taylor Swift",
        "Shake It Off - Taylor Swift",
        "You Belong with Me - Taylor Swift",
        "Love Story - Taylor Swift",
        "Watermelon Sugar - Harry Styles",
        "As It Was - Harry Styles",
        "Sign of the Times - Harry Styles",
        "Adore You - Harry Styles",
        "Golden - Harry Styles",
        "Butter - BTS",
        "Dynamite - BTS",
        "Permission to Dance - BTS",
        "Boy with Luv - BTS",
        "Fake Love - BTS",
        "IDOL - BTS",
        "On - BTS",
        "Life Goes On - BTS",
        "Spring Day - BTS",
        "Euphoria - BTS",
        "DNA - BTS",
        "MIC Drop - BTS",
        "Lalisa - Lisa",
        "Money - Lisa",
        "Kill This Love - BLACKPINK",
        "How You Like That - BLACKPINK",
        "Ddu-Du Ddu-Du - BLACKPINK",
        "Boombayah - BLACKPINK",
        "Whistle - BLACKPINK",
        "Playing with Fire - BLACKPINK",
        "Forever Young - BLACKPINK",
        "Ice Cream - BLACKPINK",
        "Lovesick Girls - BLACKPINK",
        "On the Ground - Rosé",
        "Gone - Rosé",
        "Solo - Jennie",
        "Shallow - Lady Gaga",
        "Rain on Me - Lady Gaga",
        "Poker Face - Lady Gaga",
        "Bad Romance - Lady Gaga",
        "Just Dance - Lady Gaga",
        "Born This Way - Lady Gaga",
        "Always Remember Us This Way - Lady Gaga",
        "Million Reasons - Lady Gaga",
        "The Edge of Glory - Lady Gaga",
        "Applause - Lady Gaga",
        "Paparazzi - Lady Gaga",
        "Alejandro - Lady Gaga",
        "Telephone - Lady Gaga",
        "Speechless - Lady Gaga",
        "Aura - Lady Gaga",
        "Venus - Lady Gaga",
        "Do What U Want - Lady Gaga",
        "Fashion! - Lady Gaga",
        "ARTPOP - Lady Gaga",
        "Swine - Lady Gaga",
        "Gypsy - Lady Gaga",
        "Mary Jane Holland - Lady Gaga",
        "Dope - Lady Gaga",
        "Brooklyn Nights - Lady Gaga",
        "Chandelier - Sia",
        "Elastic Heart - Sia",
        "Cheap Thrills - Sia",
        "Unstoppable - Sia",
        "Titanium - David Guetta ft. Sia",
        "Alive - Sia",
        "Together - Sia",
        "Dusk Till Dawn - ZAYN ft. Sia",
        "Beautiful People - Ed Sheeran ft. Khalid",
        "I Don't Care - Ed Sheeran ft. Justin Bieber",
        "Photograph - Ed Sheeran",
        "Thinking Out Loud - Ed Sheeran",
        "Castle on the Hill - Ed Sheeran",
        "Galway Girl - Ed Sheeran",
        "Dive - Ed Sheeran",
        "Happier - Ed Sheeran",
        "Supermarket Flowers - Ed Sheeran",
        "Perfect Symphony - Ed Sheeran & Andrea Bocelli",
        "Perfect Duet - Ed Sheeran & Beyoncé",
        "Afterglow - Ed Sheeran",
        "Cross Me - Ed Sheeran ft. Chance the Rapper",
        "South of the Border - Ed Sheeran ft. Camila Cabello & Cardi B",
        "Best Part of Me - Ed Sheeran ft. YEBBA",
        "Blow - Ed Sheeran, Chris Stapleton & Bruno Mars",
        "Feels - Calvin Harris ft. Pharrell Williams, Katy Perry & Big Sean",
        "This Is What You Came For - Calvin Harris ft. Rihanna",
        "We Found Love - Calvin Harris ft. Rihanna",
        "Summer - Calvin Harris",
        "Slide - Calvin Harris ft. Frank Ocean & Migos",
        "One Kiss - Calvin Harris & Dua Lipa",
        "Giant - Calvin Harris & Rag'n'Bone Man",
        "Blame - Calvin Harris ft. John Newman",
        "Outside - Calvin Harris ft. Ellie Goulding",
        "I Need Your Love - Calvin Harris ft. Ellie Goulding",
        "Pray to God - Calvin Harris ft. HAIM",
        "Sweet Nothing - Calvin Harris ft. Florence Welch",
        "I'm Not Alone - Calvin Harris",
        "Bounce - Calvin Harris ft. Kelis",
        "Feel So Close - Calvin Harris",
        "Let's Go - Calvin Harris ft. Ne-Yo",
        "Acceptable in the 80s - Calvin Harris",
        "Ready for the Weekend - Calvin Harris",
        "Thinking About You - Calvin Harris ft. Ayah Marar",
        "My Way - Calvin Harris",
        "How Deep Is Your Love - Calvin Harris & Disciples",
        "Love Now - Calvin Harris ft. All About She",
        "Hype - Calvin Harris ft. Dizzee Rascal",
        "Hard to Love - Calvin Harris ft. Jessie Reyez",
        "Rollin - Calvin Harris ft. Future & Khalid",
        "Faking It - Calvin Harris ft. Kehlani & Lil Yachty",
        "Heatstroke - Calvin Harris ft. Young Thug, Pharrell Williams & Ariana Grande",
        "Open Wide - Calvin Harris ft. Big Sean",
        "5AM - Calvin Harris",
        "It Was You - Calvin Harris & Disciples",
        "Iron - Calvin Harris ft. Nicky Romero",
    )
}

